// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3mcT9zOcWXpa4V_y2YAKKes9L79JyFK8',
    appId: '1:470765701147:web:a2d620b3964e387dd550be',
    messagingSenderId: '470765701147',
    projectId: 'thppy-limkokwing',
    authDomain: 'thppy-limkokwing.firebaseapp.com',
    storageBucket: 'thppy-limkokwing.appspot.com',
    measurementId: 'G-T5KL6EZEGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg6Zfxf6tOMLRCd_PSZOB7SK1QNblwe9Q',
    appId: '1:470765701147:android:b767db8c580ac308d550be',
    messagingSenderId: '470765701147',
    projectId: 'thppy-limkokwing',
    storageBucket: 'thppy-limkokwing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPk63px8PC-VUnS5UG38Qegmeq9fC1o8M',
    appId: '1:470765701147:ios:761027e1bc1ca8a0d550be',
    messagingSenderId: '470765701147',
    projectId: 'thppy-limkokwing',
    storageBucket: 'thppy-limkokwing.appspot.com',
    iosClientId: '470765701147-g4i2puulnlnrn005mbb6fj5a89sk2orp.apps.googleusercontent.com',
    iosBundleId: 'com.example.thppyAdministration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPk63px8PC-VUnS5UG38Qegmeq9fC1o8M',
    appId: '1:470765701147:ios:761027e1bc1ca8a0d550be',
    messagingSenderId: '470765701147',
    projectId: 'thppy-limkokwing',
    storageBucket: 'thppy-limkokwing.appspot.com',
    iosClientId: '470765701147-g4i2puulnlnrn005mbb6fj5a89sk2orp.apps.googleusercontent.com',
    iosBundleId: 'com.example.thppyAdministration',
  );
}
